name: Build Extension ZIP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node (optional)
        uses: actions/setup-node@v3

      - name: Create dist Directory
        run: mkdir -p dist

      - name: Zip Extension Files
        run: zip -r dist/drasticpicker.zip extension/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: drasticpicker-zip
          path: dist/drasticpicker.zip
